function setScreenSize(n,t){var r=parseInt(n),i;r=r==NaN?-1:r;i=parseInt(t);i=i==NaN?-1:i;Ormma._setScreenSize(r,i)}function setDefaultExpandProperties(n,t){var r=parseInt(n),i;r=r==NaN?-1:r;i=parseInt(t);i=i==NaN?-1:i;Ormma._setDefaultExpandProperties(r,i)}function invokeInit(){Ormma.getState()==ORMMA_EVENT_LOADING&&Ormma._setState(ORMMA_STATE_DEFAULT);Ormma._init()}function reportError(n,t){Ormma._throwError(n,t)}function setPayload(n,t,i,r){var u="",f="",e="";try{u=JSON.parse(n)}catch(o){}try{f=JSON.parse(t)}catch(o){}try{r!=null&&typeof r=="string"&&(e=JSON.parse(r))}catch(o){}microsoft.advertising.payload={ad:u,prm:f,container:i,appOptions:e}}function sendRendererMessage(n,t){Ormma._sendRendererMessage(n,t)}function setSdkVersion(n,t,i){_sdkInfo={sdkVersion:n,client:t,runtimeType:i,appName:navigator.appName,userAgent:navigator.userAgent,appVersion:navigator.appVersion,platform:navigator.platform}}function setOrmmaState(n){Ormma._setState(n)}function setSize(n,t){var r=parseInt(n),i;r=r==NaN?-1:r;i=parseInt(t);i=i==NaN?-1:i;Ormma._setSize(r,i)}function setMaxSize(n,t){var r=parseInt(n),i;r=r==NaN?-1:r;i=parseInt(t);i=i==NaN?-1:i;Ormma._setMaxSize(r,i)}function setDefaultPosition(n,t,i,r){var o=parseInt(n),u,f,e;o=o==NaN?-1:o;u=parseInt(t);u=u==NaN?-1:u;f=parseInt(i);f=f==NaN?-1:f;e=parseInt(r);e=e==NaN?-1:e;Ormma._setDefaultPosition(n,t,i,r)}function setOrientation(n){var t=parseInt(n);t=t==NaN?-1:t;Ormma._setOrientation(t)}function setNetwork(n){Ormma._setNetwork(n)}function setTilt(n,t,i){var f=parseFloat(n),r,u;f=f==NaN?0:f;r=parseFloat(t);r=r==NaN?0:r;u=parseFloat(i);u=u==NaN?0:u;Ormma._setTilt(f,r,u)}function setIsViewable(n){var t=stringToBoolean(n);Ormma._setIsViewable(t)}function setCapability(n,t){n==ORMMA_FEATURE_MAP&&(Ormma._mapCapability=stringToBoolean(t))}function fireResponse(n,t){var i={url:escape(n),response:escape(t)};Ormma._sendResponse(i)}function stringToBoolean(n){return n.toLowerCase()=="false"?!1:n.toLowerCase()=="true"?!0:undefined}function setOrmmaLocale(n){Ormma._setLocale(n)}var ORMMA_STATE_UNKNOWN="unknown",ORMMA_STATE_HIDDEN="hidden",ORMMA_STATE_DEFAULT="default",ORMMA_STATE_EXPANDED="expanded",ORMMA_STATE_RESIZED="resized",ORMMA_EVENT_ERROR="error",ORMMA_EVENT_HEADING_CHANGE="headingChange",ORMMA_EVENT_KEYBOARD_CHANGE="keyboardChange",ORMMA_EVENT_LOCATION_CHANGE="locationChange",ORMMA_EVENT_NETWORK_CHANGE="networkChange",ORMMA_EVENT_ORIENTATION_CHANGE="orientationChange",ORMMA_EVENT_READY="ready",ORMMA_EVENT_LOADING="loading",ORMMA_EVENT_RESPONSE="response",ORMMA_EVENT_SCREEN_CHANGE="screenChange",ORMMA_EVENT_SHAKE="shake",ORMMA_EVENT_SIZE_CHANGE="sizeChange",ORMMA_EVENT_STATE_CHANGE="stateChange",ORMMA_EVENT_TILT_CHANGE="tiltChange",ORMMA_EVENT_VIEWABLE_CHANGE="viewableChange",ORMMA_EVENT_RENDERER_MESSAGE="rendererMessage",ORMMA_FEATURE_SCREEN="screen",ORMMA_FEATURE_ORIENTATION="orientation",ORMMA_FEATURE_LOCATION="location",ORMMA_FEATURE_SMS="sms",ORMMA_FEATURE_PHONE="phone",ORMMA_FEATURE_EMAIL="email",ORMMA_FEATURE_HEADING="heading",ORMMA_FEATURE_SHAKE="shake",ORMMA_FEATURE_TILT="tilt",ORMMA_FEATURE_NETWORK="network",ORMMA_FEATURE_CALENDAR="calendar",ORMMA_FEATURE_CAMERA="camera",ORMMA_FEATURE_MAP="map",ORMMA_FEATURE_AUDIO="audio",ORMMA_FEATURE_VIDEO="video",ORMMA_FEATURE_LEVEL1="level-1",ORMMA_FEATURE_LEVEL2="level-2",ORMMA_FEATURE_LEVEL3="level-3",ORMMA_VERSION="1.1.0",MRAID_VERSION="1.0",MRAID_FEATURE_LEVEL1="level-1",ORMMA_NETWORK_STATE_UNKNOWN="unknown",MAPLE_MAX_STATE_DATA_SIZE=65536,_sdkInfo=null,_placementType="inline",microsoft;(function(){function f(){this.listeners=[]}function t(){}function u(){return typeof window.external=="object"&&typeof window.external.notify!="undefined"}function n(n){u()&&window.external.notify(n)}function i(i,u){var e,f;if(r.listeners[i]!=null){e=r.listeners[i].slice();switch(i){case ORMMA_EVENT_ERROR:for(f=0;f<e.length;f++)e[f](u.message,u.action);break;case ORMMA_EVENT_NETWORK_CHANGE:for(f=0;f<e.length;f++)e[f](u.online,u.connection);break;case ORMMA_EVENT_ORIENTATION_CHANGE:for(f=0;f<e.length;f++)e[f](u);break;case ORMMA_EVENT_READY:for(f=0;f<e.length;f++)e[f]();break;case ORMMA_EVENT_SCREEN_CHANGE:for(f=0;f<e.length;f++)e[f](u.width,u.height);break;case ORMMA_EVENT_SHAKE:for(f=0;f<e.length;f++)e[f]();break;case ORMMA_EVENT_SIZE_CHANGE:for(f=0;f<e.length;f++)e[f](u.width,u.height);break;case ORMMA_EVENT_STATE_CHANGE:for(f=0;f<e.length;f++)e[f](u);break;case ORMMA_EVENT_TILT_CHANGE:for(f=0;f<e.length;f++)e[f](u.x,u.y,u.z);break;case ORMMA_EVENT_VIEWABLE_CHANGE:for(t("_fireevent: "+ORMMA_EVENT_VIEWABLE_CHANGE+" "+e.length),f=0;f<e.length;f++)e[f](u);break;case ORMMA_EVENT_RESPONSE:for(f=0;f<e.length;f++)e[f](unescape(u.url),unescape(u.response));break;case ORMMA_EVENT_RENDERER_MESSAGE:for(f=0;f<e.length;f++)e[f](u.type,u.data);break;case ORMMA_EVENT_HEADING_CHANGE:case ORMMA_EVENT_KEYBOARD_CHANGE:case ORMMA_EVENT_LOCATION_CHANGE:default:return!1}}else i==ORMMA_EVENT_RENDERER_MESSAGE?n("rendererMessage:error=Ad is not subscribed to the changes."):t("no listeners for event "+i)}var r=new f;window.ORMMA=window.ormma=window.Ormma=window.MAPLE=window.maple=window.Maple=window.mraid=window.MRAID={_maxSize:{},_dimensions:{},_defaultDimensions:{},_screenSize:{},_shakeCapability:!1,_mapCapability:!1,_isViewable:undefined,_state:ORMMA_EVENT_LOADING,_location:null,_tilt:{},_orientation:-1,_network:ORMMA_NETWORK_STATE_UNKNOWN,_locale:null,_isUserEngaged:!1,_adInstanceState:null,storeAdInstanceState:function(n){typeof n=="string"?n.length<=MAPLE_MAX_STATE_DATA_SIZE?this._adInstanceState=n:this._throwError("storeAdInstanceState","attempting to store state data greater than allowed length of "+MAPLE_MAX_STATE_DATA_SIZE+", attempted store length "+n.length):this._throwError("storeAdInstanceState","attempting to store state data that is not a string")},getAdInstanceState:function(){if(this._adInstanceState!==null)return this._adInstanceState},getSdkVersion:function(){if(_sdkInfo!==null)return _sdkInfo},getVersion:function(){return MRAID_VERSION},getPlacementType:function(){return _placementType},setUserEngaged:function(i){this._isUserEngaged=typeof i=="boolean"?i:!1;t("setting user engaged: "+this._isUserEngaged);n("setuserengaged:engaged="+this._isUserEngaged)},getLocale:function(){if(this._locale!==null)return this._locale},_setLocale:function(n){this._locale=n},_expandProperties:{width:480,height:800,useCustomClose:!1,lockOrientation:!1,isModal:!0},useCustomClose:function(i){typeof i=="boolean"?(t("calling usecustomclose:"+i),n("usecustomclose:"+i),this._expandProperties.useCustomClose=i):reportError("useCustomClose","parameter 'flag' is not a boolean value")},adError:function(t,i){var r,u;r=typeof t=="string"&&t!==null&&t!==""?t:"unknown action";u=typeof i=="string"&&i!==null&&i!==""?i:"an unknown error occurred.";n("aderror:action="+encodeURIComponent(r)+"&msg="+encodeURIComponent(u))},addEventListener:function(t,i){r.listeners[t]==null&&(r.listeners[t]=[]);r.listeners[t].push(i);switch(t){case ORMMA_EVENT_NETWORK_CHANGE:n("network:listener=start");break;case ORMMA_EVENT_TILT_CHANGE:n("tilt:listener=start");break;case ORMMA_EVENT_ORIENTATION_CHANGE:n("getOrientation:listener=start");break;case ORMMA_EVENT_VIEWABLE_CHANGE:n("viewableChange:listener=start")}},close:function(){t("sending close request");n("close")},createEvent:function(){},expand:function(i){if(!(this.getState()==ORMMA_STATE_DEFAULT||this.getState()==ORMMA_STATE_RESIZED)){Ormma._throwError("expand","cannot expand from non-default state");return}if((i==undefined||i==null)&&(i=""),u())t("url is "+i),n("expand:url="+encodeURIComponent(i));else{var r={url:i};n("expand:"+JSON.stringify(r))}},getDefaultPosition:function(){return this._defaultDimensions},getExpandProperties:function(){return this._expandProperties},getHeading:function(){return-1},getKeyboard:function(){return!1},getLocation:function(){return this._location},getMaxSize:function(){return this._maxSize},getNetwork:function(){return n("network"),this._network},getOrientation:function(){return n("getorientation"),this._orientation},getScreenSize:function(){return this._screenSize==null&&(this._screenSize={width:screen.width,height:screen.height}),this._screenSize},getSize:function(){return typeof this._dimensions=="undefined"&&(this._dimensions={}),this._dimensions},getState:function(){return this._state},getTilt:function(){return n("tilt"),this._tilt},isViewable:function(){return n("isviewable"),this._isViewable},hide:function(){t("calling hide");n("hide")},open:function(i){t("sending website request: "+i);n("web:url="+encodeURIComponent(i))},removeEventListener:function(i,u){var f,e,o;if(t("removing listener for "+i),r.listeners[i]!=null){if(f=r.listeners[i],u==null)while(f.length>0)f.pop();else for(e=0;e<f.length;e++)if(f[e]==u){o=f.splice(e,1);break}r.listeners[i].length==0&&(i==ORMMA_EVENT_NETWORK_CHANGE?n("network:listener=stop"):i==ORMMA_EVENT_TILT_CHANGE?n("tilt:listener=stop"):i==ORMMA_EVENT_VIEWABLE_CHANGE&&n("viewableChange:listener=stop"))}},request:function(t,i){var r={url:t,display:typeof i!="undefined"&&i!==null?i:"ignore"};return n("request:url="+encodeURIComponent(t)+"&display="+r.display),!1},setExpandProperties:function(i){var u,f,r;if(typeof i=="object"){u=["width","height","useCustomClose","isModal","lockOrientation"];for(f in u)r=u[f],i[r]!==undefined&&(this._expandProperties[r]=i[r])}t("setting expand properties: width="+this._expandProperties.width+"&height="+this._expandProperties.height+"&usecustomclose="+this._expandProperties.useCustomClose+"&lockorientation="+this._expandProperties.lockOrientation);n("setexpandproperties:width="+this._expandProperties.width+"&height="+this._expandProperties.height+"&usecustomclose="+this._expandProperties.useCustomClose+"&lockorientation="+this._expandProperties.lockOrientation)},show:function(){t("calling show");n("show")},supports:function(n){switch(n){case ORMMA_FEATURE_SCREEN:case ORMMA_FEATURE_ORIENTATION:case ORMMA_FEATURE_TILT:case ORMMA_FEATURE_AUDIO:case ORMMA_FEATURE_VIDEO:case MRAID_FEATURE_LEVEL1:return!0;case ORMMA_FEATURE_PHONE:case ORMMA_FEATURE_MAP:case ORMMA_FEATURE_NETWORK:case ORMMA_FEATURE_SHAKE:case ORMMA_FEATURE_SMS:case ORMMA_FEATURE_EMAIL:case ORMMA_FEATURE_HEADING:case ORMMA_FEATURE_LOCATION:case ORMMA_FEATURE_CALENDAR:case ORMMA_FEATURE_CAMERA:case ORMMA_FEATURE_LEVEL2:case ORMMA_FEATURE_LEVEL3:default:return!1}},playVideo:function(i){t("sending video request: "+i);n("media:url="+encodeURIComponent(i))},playAudio:function(i){t("sending audio request: "+i);n("media:url="+encodeURIComponent(i))},publisherMessage:function(t,i){typeof t=="string"&&typeof i=="string"&&n("publisherMessage:type="+encodeURIComponent(t)+"&data="+encodeURIComponent(i))},_tiltChange:function(){},_orientationChange:function(){},_networkChange:function(){},_headingChange:function(){},_locationChanged:function(){},_throwError:function(n,t){var r={message:t,action:n};i(ORMMA_EVENT_ERROR,r)},_sendRendererMessage:function(n,t){var r={type:n,data:t};i(ORMMA_EVENT_RENDERER_MESSAGE,r)},_init:function(){t("Ormma is ready");i(ORMMA_EVENT_READY,null);typeof window.ORMMAReady=="function"&&(t("Ormma calling ORMMAReady()"),window.ORMMAReady())},_setNetwork:function(n){var u=this._network,t,r;this._network=n;u!=this._network&&(t=this._network=="wifi"||this._network=="cell",r={online:t,connection:this._network},i(ORMMA_EVENT_NETWORK_CHANGE,r))},_setTilt:function(n,t,r){var u=this._tilt;this._tilt={x:n,y:t,z:r};(u.x!=this._tilt.x||u.y!=this._tilt.y||u.z!=this._tilt.z)&&i(ORMMA_EVENT_TILT_CHANGE,this._tilt)},_setOrientation:function(n){var t=this._orientation;this._orientation=n;t!=this._orientation&&i(ORMMA_EVENT_ORIENTATION_CHANGE,this._orientation)},_setState:function(n){var r=this._state;this._state=n;r!=n&&(t("changing state to "+n),i(ORMMA_EVENT_STATE_CHANGE,this._state))},_setSize:function(n,t){typeof this._dimensions=="undefined"&&(this._dimensions={});var r=this._dimensions.width==undefined?0:this._dimensions.width,u=this._dimensions.height==undefined?0:this._dimensions.height;this._dimensions.width=n;this._dimensions.height=t;(r!=n||u!=t)&&i(ORMMA_EVENT_SIZE_CHANGE,this._dimensions)},_setMaxSize:function(n,t){typeof this._maxSize=="undefined"&&(this._maxSize={});this._maxSize.width=n;this._maxSize.height=t},_setScreenSize:function(n,t){var r=this.getScreenSize();this._screenSize.width=n;this._screenSize.height=t;(r.width!=this._screenSize.width||r.height!=this._screenSize.height)&&i(ORMMA_EVENT_SCREEN_CHANGE,this._screenSize)},_setDefaultExpandProperties:function(n,t){this._expandProperties.width=n;this._expandProperties.height=t},_setDefaultPosition:function(n,t,i,r){typeof this._defaultDimensions=="undefined"&&(this._defaultDimensions={});this._defaultDimensions.x=n;this._defaultDimensions.y=t;this._defaultDimensions.width=i;this._defaultDimensions.height=r},_setIsViewable:function(n){this._isViewable!=n&&(this._isViewable=n,i(ORMMA_EVENT_VIEWABLE_CHANGE,this._isViewable))},_sendResponse:function(n){i(ORMMA_EVENT_RESPONSE,n)},externalLog:function(n){t(n)}}})();microsoft&&microsoft.advertising&&microsoft.advertising.payload||(microsoft={},microsoft.advertising={},microsoft.advertising.payload={});
// SIG // Begin signature block
// SIG // MIIanwYJKoZIhvcNAQcCoIIakDCCGowCAQExCzAJBgUr
// SIG // DgMCGgUAMGcGCisGAQQBgjcCAQSgWTBXMDIGCisGAQQB
// SIG // gjcCAR4wJAIBAQQQEODJBs441BGiowAQS9NQkAIBAAIB
// SIG // AAIBAAIBAAIBADAhMAkGBSsOAwIaBQAEFOOhMdOTkDSD
// SIG // pID4ls3H2sJqwTwooIIVgjCCBMMwggOroAMCAQICEzMA
// SIG // AABMoehNzLR0ezsAAAAAAEwwDQYJKoZIhvcNAQEFBQAw
// SIG // dzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEhMB8GA1UEAxMYTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgUENBMB4XDTEzMTExMTIy
// SIG // MTEzMVoXDTE1MDIxMTIyMTEzMVowgbMxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xDTALBgNVBAsTBE1PUFIxJzAlBgNVBAsT
// SIG // Hm5DaXBoZXIgRFNFIEVTTjpDMEY0LTMwODYtREVGODEl
// SIG // MCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
// SIG // dmljZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
// SIG // ggEBALHY+hsGK3eo5JRdfA/meqaS7opUHaT5hHWFl8zL
// SIG // XJbQ13Ut2Qj7W9LuLSXGNz71q34aU+VXvmvov8qWCtxG
// SIG // 8VoePgLSsuAmjgBke748k/hYMnmH0hpdI7ycUcQPEPoE
// SIG // WLUWdm7svMblvvytrMFB26rOefUcsplBp3olK/+reA1Y
// SIG // OrFeUN5kTODKFSrfpun+pGYvWxAJCSYh1D8NL23S+HeQ
// SIG // A2zeFBKljOc2H/SHpbBBF2/jTXRmwv2icUY1UcxrF1Fj
// SIG // +hWUkppfSyi65hZFSekstf6Lh6/8pW1D3KYw+iko75sN
// SIG // LFyD3hKNarTbce9cFFoqIyj/gXBX8YwHmhPYKlMCAwEA
// SIG // AaOCAQkwggEFMB0GA1UdDgQWBBS5Da2zTfTanxqyJyZV
// SIG // DSBE2Jji9DAfBgNVHSMEGDAWgBQjNPjZUkZwCu1A+3b7
// SIG // syuwwzWzDzBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
// SIG // Y3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0
// SIG // cy9NaWNyb3NvZnRUaW1lU3RhbXBQQ0EuY3JsMFgGCCsG
// SIG // AQUFBwEBBEwwSjBIBggrBgEFBQcwAoY8aHR0cDovL3d3
// SIG // dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNyb3Nv
// SIG // ZnRUaW1lU3RhbXBQQ0EuY3J0MBMGA1UdJQQMMAoGCCsG
// SIG // AQUFBwMIMA0GCSqGSIb3DQEBBQUAA4IBAQAJik4Gr+jt
// SIG // gs8dB37XKqckCy2vmlskf5RxDFWIJBpSFWPikE0FSphK
// SIG // nPvhp21oVYK5KeppqbLV4wza0dZ6JTd4ZxwM+9spWhqX
// SIG // OCo5Vkb7NYG55D1GWo7k/HU3WFlJi07bPBWdc1JL63sM
// SIG // OsItwbObUi3gNcW5wVez6D2hPETyIxYeCqpZNyfQlVJe
// SIG // qH8/VPCB4dyavWXVePb3TDm73eDWNw6RmoeMc+dxZFL3
// SIG // PgPYxs1yuDQ0mFuM0/UIput4xlGgDQ5v9Gs8QBpgFiyp
// SIG // BlKdHBOQzm8CHup7nLP2+Jdg8mXR0R+HOsF18EKNeu2M
// SIG // crJ7+yyKtJFHVOIuacwWVBpZMIIE7DCCA9SgAwIBAgIT
// SIG // MwAAAMps1TISNcThVQABAAAAyjANBgkqhkiG9w0BAQUF
// SIG // ADB5MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
// SIG // Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
// SIG // TWljcm9zb2Z0IENvcnBvcmF0aW9uMSMwIQYDVQQDExpN
// SIG // aWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQTAeFw0xNDA0
// SIG // MjIxNzM5MDBaFw0xNTA3MjIxNzM5MDBaMIGDMQswCQYD
// SIG // VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
// SIG // A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
// SIG // IENvcnBvcmF0aW9uMQ0wCwYDVQQLEwRNT1BSMR4wHAYD
// SIG // VQQDExVNaWNyb3NvZnQgQ29ycG9yYXRpb24wggEiMA0G
// SIG // CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCWcV3tBkb6
// SIG // hMudW7dGx7DhtBE5A62xFXNgnOuntm4aPD//ZeM08aal
// SIG // IV5WmWxY5JKhClzC09xSLwxlmiBhQFMxnGyPIX26+f4T
// SIG // UFJglTpbuVildGFBqZTgrSZOTKGXcEknXnxnyk8ecYRG
// SIG // vB1LtuIPxcYnyQfmegqlFwAZTHBFOC2BtFCqxWfR+nm8
// SIG // xcyhcpv0JTSY+FTfEjk4Ei+ka6Wafsdi0dzP7T00+Lnf
// SIG // NTC67HkyqeGprFVNTH9MVsMTC3bxB/nMR6z7iNVSpR4o
// SIG // +j0tz8+EmIZxZRHPhckJRIbhb+ex/KxARKWpiyM/gkmd
// SIG // 1ZZZUBNZGHP/QwytK9R/MEBnAgMBAAGjggFgMIIBXDAT
// SIG // BgNVHSUEDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQUH17i
// SIG // XVCNVoa+SjzPBOinh7XLv4MwUQYDVR0RBEowSKRGMEQx
// SIG // DTALBgNVBAsTBE1PUFIxMzAxBgNVBAUTKjMxNTk1K2I0
// SIG // MjE4ZjEzLTZmY2EtNDkwZi05YzQ3LTNmYzU1N2RmYzQ0
// SIG // MDAfBgNVHSMEGDAWgBTLEejK0rQWWAHJNy4zFha5TJoK
// SIG // HzBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1p
// SIG // Y3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWND
// SIG // b2RTaWdQQ0FfMDgtMzEtMjAxMC5jcmwwWgYIKwYBBQUH
// SIG // AQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3Lm1p
// SIG // Y3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY0NvZFNpZ1BD
// SIG // QV8wOC0zMS0yMDEwLmNydDANBgkqhkiG9w0BAQUFAAOC
// SIG // AQEAd1zr15E9zb17g9mFqbBDnXN8F8kP7Tbbx7UsG177
// SIG // VAU6g3FAgQmit3EmXtZ9tmw7yapfXQMYKh0nfgfpxWUf
// SIG // tc8Nt1THKDhaiOd7wRm2VjK64szLk9uvbg9dRPXUsO8b
// SIG // 1U7Brw7vIJvy4f4nXejF/2H2GdIoCiKd381wgp4Yctgj
// SIG // zHosQ+7/6sDg5h2qnpczAFJvB7jTiGzepAY1p8JThmUR
// SIG // dwmPNVm52IaoAP74MX0s9IwFncDB1XdybOlNWSaD8cKy
// SIG // iFeTNQB8UCu8Wfz+HCk4gtPeUpdFKRhOlludul8bo/En
// SIG // UOoHlehtNA04V9w3KDWVOjic1O1qhV0OIhFeezCCBbww
// SIG // ggOkoAMCAQICCmEzJhoAAAAAADEwDQYJKoZIhvcNAQEF
// SIG // BQAwXzETMBEGCgmSJomT8ixkARkWA2NvbTEZMBcGCgmS
// SIG // JomT8ixkARkWCW1pY3Jvc29mdDEtMCsGA1UEAxMkTWlj
// SIG // cm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
// SIG // MB4XDTEwMDgzMTIyMTkzMloXDTIwMDgzMTIyMjkzMlow
// SIG // eTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
// SIG // b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
// SIG // Y3Jvc29mdCBDb3Jwb3JhdGlvbjEjMCEGA1UEAxMaTWlj
// SIG // cm9zb2Z0IENvZGUgU2lnbmluZyBQQ0EwggEiMA0GCSqG
// SIG // SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCycllcGTBkvx2a
// SIG // YCAgQpl2U2w+G9ZvzMvx6mv+lxYQ4N86dIMaty+gMuz/
// SIG // 3sJCTiPVcgDbNVcKicquIEn08GisTUuNpb15S3GbRwfa
// SIG // /SXfnXWIz6pzRH/XgdvzvfI2pMlcRdyvrT3gKGiXGqel
// SIG // cnNW8ReU5P01lHKg1nZfHndFg4U4FtBzWwW6Z1KNpbJp
// SIG // L9oZC/6SdCnidi9U3RQwWfjSjWL9y8lfRjFQuScT5EAw
// SIG // z3IpECgixzdOPaAyPZDNoTgGhVxOVoIoKgUyt0vXT2Pn
// SIG // 0i1i8UU956wIAPZGoZ7RW4wmU+h6qkryRs83PDietHdc
// SIG // pReejcsRj1Y8wawJXwPTAgMBAAGjggFeMIIBWjAPBgNV
// SIG // HRMBAf8EBTADAQH/MB0GA1UdDgQWBBTLEejK0rQWWAHJ
// SIG // Ny4zFha5TJoKHzALBgNVHQ8EBAMCAYYwEgYJKwYBBAGC
// SIG // NxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQU/dExTtMm
// SIG // ipXhmGA7qDFvpjy82C0wGQYJKwYBBAGCNxQCBAweCgBT
// SIG // AHUAYgBDAEEwHwYDVR0jBBgwFoAUDqyCYEBWJ5flJRP8
// SIG // KuEKU5VZ5KQwUAYDVR0fBEkwRzBFoEOgQYY/aHR0cDov
// SIG // L2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVj
// SIG // dHMvbWljcm9zb2Z0cm9vdGNlcnQuY3JsMFQGCCsGAQUF
// SIG // BwEBBEgwRjBEBggrBgEFBQcwAoY4aHR0cDovL3d3dy5t
// SIG // aWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNyb3NvZnRS
// SIG // b290Q2VydC5jcnQwDQYJKoZIhvcNAQEFBQADggIBAFk5
// SIG // Pn8mRq/rb0CxMrVq6w4vbqhJ9+tfde1MOy3XQ60L/svp
// SIG // LTGjI8x8UJiAIV2sPS9MuqKoVpzjcLu4tPh5tUly9z7q
// SIG // QX/K4QwXaculnCAt+gtQxFbNLeNK0rxw56gNogOlVuC4
// SIG // iktX8pVCnPHz7+7jhh80PLhWmvBTI4UqpIIck+KUBx3y
// SIG // 4k74jKHK6BOlkU7IG9KPcpUqcW2bGvgc8FPWZ8wi/1wd
// SIG // zaKMvSeyeWNWRKJRzfnpo1hW3ZsCRUQvX/TartSCMm78
// SIG // pJUT5Otp56miLL7IKxAOZY6Z2/Wi+hImCWU4lPF6H0q7
// SIG // 0eFW6NB4lhhcyTUWX92THUmOLb6tNEQc7hAVGgBd3TVb
// SIG // Ic6YxwnuhQ6MT20OE049fClInHLR82zKwexwo1eSV32U
// SIG // jaAbSANa98+jZwp0pTbtLS8XyOZyNxL0b7E8Z4L5UrKN
// SIG // MxZlHg6K3RDeZPRvzkbU0xfpecQEtNP7LN8fip6sCvsT
// SIG // J0Ct5PnhqX9GuwdgR2VgQE6wQuxO7bN2edgKNAltHIAx
// SIG // H+IOVN3lofvlRxCtZJj/UBYufL8FIXrilUEnacOTj5XJ
// SIG // jdibIa4NXJzwoq6GaIMMai27dmsAHZat8hZ79haDJLmI
// SIG // z2qoRzEvmtzjcT3XAH5iR9HOiMm4GPoOco3Boz2vAkBq
// SIG // /2mbluIQqBC0N1AI1sM9MIIGBzCCA++gAwIBAgIKYRZo
// SIG // NAAAAAAAHDANBgkqhkiG9w0BAQUFADBfMRMwEQYKCZIm
// SIG // iZPyLGQBGRYDY29tMRkwFwYKCZImiZPyLGQBGRYJbWlj
// SIG // cm9zb2Z0MS0wKwYDVQQDEyRNaWNyb3NvZnQgUm9vdCBD
// SIG // ZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMDcwNDAzMTI1
// SIG // MzA5WhcNMjEwNDAzMTMwMzA5WjB3MQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMSEwHwYDVQQDExhNaWNyb3NvZnQgVGltZS1T
// SIG // dGFtcCBQQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
// SIG // ggEKAoIBAQCfoWyx39tIkip8ay4Z4b3i48WZUSNQrc7d
// SIG // GE4kD+7Rp9FMrXQwIBHrB9VUlRVJlBtCkq6YXDAm2gBr
// SIG // 6Hu97IkHD/cOBJjwicwfyzMkh53y9GccLPx754gd6udO
// SIG // o6HBI1PKjfpFzwnQXq/QsEIEovmmbJNn1yjcRlOwhtDl
// SIG // KEYuJ6yGT1VSDOQDLPtqkJAwbofzWTCd+n7Wl7PoIZd+
// SIG // +NIT8wi3U21StEWQn0gASkdmEScpZqiX5NMGgUqi+YSn
// SIG // EUcUCYKfhO1VeP4Bmh1QCIUAEDBG7bfeI0a7xC1Un68e
// SIG // eEExd8yb3zuDk6FhArUdDbH895uyAc4iS1T/+QXDwiAL
// SIG // AgMBAAGjggGrMIIBpzAPBgNVHRMBAf8EBTADAQH/MB0G
// SIG // A1UdDgQWBBQjNPjZUkZwCu1A+3b7syuwwzWzDzALBgNV
// SIG // HQ8EBAMCAYYwEAYJKwYBBAGCNxUBBAMCAQAwgZgGA1Ud
// SIG // IwSBkDCBjYAUDqyCYEBWJ5flJRP8KuEKU5VZ5KShY6Rh
// SIG // MF8xEzARBgoJkiaJk/IsZAEZFgNjb20xGTAXBgoJkiaJ
// SIG // k/IsZAEZFgltaWNyb3NvZnQxLTArBgNVBAMTJE1pY3Jv
// SIG // c29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eYIQ
// SIG // ea0WoUqgpa1Mc1j0BxMuZTBQBgNVHR8ESTBHMEWgQ6BB
// SIG // hj9odHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
// SIG // bC9wcm9kdWN0cy9taWNyb3NvZnRyb290Y2VydC5jcmww
// SIG // VAYIKwYBBQUHAQEESDBGMEQGCCsGAQUFBzAChjhodHRw
// SIG // Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01p
// SIG // Y3Jvc29mdFJvb3RDZXJ0LmNydDATBgNVHSUEDDAKBggr
// SIG // BgEFBQcDCDANBgkqhkiG9w0BAQUFAAOCAgEAEJeKw1wD
// SIG // RDbd6bStd9vOeVFNAbEudHFbbQwTq86+e4+4LtQSooxt
// SIG // YrhXAstOIBNQmd16QOJXu69YmhzhHQGGrLt48ovQ7DsB
// SIG // 7uK+jwoFyI1I4vBTFd1Pq5Lk541q1YDB5pTyBi+FA+mR
// SIG // KiQicPv2/OR4mS4N9wficLwYTp2OawpylbihOZxnLcVR
// SIG // DupiXD8WmIsgP+IHGjL5zDFKdjE9K3ILyOpwPf+FChPf
// SIG // wgphjvDXuBfrTot/xTUrXqO/67x9C0J71FNyIe4wyrt4
// SIG // ZVxbARcKFA7S2hSY9Ty5ZlizLS/n+YWGzFFW6J1wlGys
// SIG // OUzU9nm/qhh6YinvopspNAZ3GmLJPR5tH4LwC8csu89D
// SIG // s+X57H2146SodDW4TsVxIxImdgs8UoxxWkZDFLyzs7BN
// SIG // Z8ifQv+AeSGAnhUwZuhCEl4ayJ4iIdBD6Svpu/RIzCzU
// SIG // 2DKATCYqSCRfWupW76bemZ3KOm+9gSd0BhHudiG/m4LB
// SIG // J1S2sWo9iaF2YbRuoROmv6pH8BJv/YoybLL+31HIjCPJ
// SIG // Zr2dHYcSZAI9La9Zj7jkIeW1sMpjtHhUBdRBLlCslLCl
// SIG // eKuzoJZ1GtmShxN1Ii8yqAhuoFuMJb+g74TKIdbrHk/J
// SIG // mu5J4PcBZW+JC33Iacjmbuqnl84xKf8OxVtc2E0bodj6
// SIG // L54/LlUWa8kTo/0xggSJMIIEhQIBATCBkDB5MQswCQYD
// SIG // VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
// SIG // A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
// SIG // IENvcnBvcmF0aW9uMSMwIQYDVQQDExpNaWNyb3NvZnQg
// SIG // Q29kZSBTaWduaW5nIFBDQQITMwAAAMps1TISNcThVQAB
// SIG // AAAAyjAJBgUrDgMCGgUAoIGiMBkGCSqGSIb3DQEJAzEM
// SIG // BgorBgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgor
// SIG // BgEEAYI3AgEVMCMGCSqGSIb3DQEJBDEWBBRjUO+/gFEk
// SIG // MKz1Pc/VnqOR73DUwDBCBgorBgEEAYI3AgEMMTQwMqAS
// SIG // gBAATwByAG0AbQBhAC4AagBzoRyAGmh0dHA6Ly93d3cu
// SIG // bWljcm9zb2Z0LmNvbS8gMA0GCSqGSIb3DQEBAQUABIIB
// SIG // AH733BiiXVRkGt6Qvt3ox/lTRnsx5nWrK0sp9FGtXvys
// SIG // 1Bg+CB3SJFrPRg3U2rz0YaJFMNaJ1ablKhxmMalJ4ksH
// SIG // K8AWlbCS/dYc1A9LEUD23JvzQo21NIIzUOM4FsixVGc0
// SIG // PnonNimDChBBSumLG/G/wQzxeZOWCjIdNBkM3+IqiIIS
// SIG // Pjkjj6cES1k8knKVV0O/ikWyPn2YCab9s4uIemqRSnsa
// SIG // 4f68jhRc2YlMYI0EkYgIOZYF8v/ibXol+SSVqO4alpSh
// SIG // paYMqE6cCp+ws2dRyJfId8P+6cV2KO0YLLl7QuqNKpGM
// SIG // XhCAMahxLYpcS1Jtz1DXWYDlGKiRlmNZszOhggIoMIIC
// SIG // JAYJKoZIhvcNAQkGMYICFTCCAhECAQEwgY4wdzELMAkG
// SIG // A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
// SIG // BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
// SIG // dCBDb3Jwb3JhdGlvbjEhMB8GA1UEAxMYTWljcm9zb2Z0
// SIG // IFRpbWUtU3RhbXAgUENBAhMzAAAATKHoTcy0dHs7AAAA
// SIG // AABMMAkGBSsOAwIaBQCgXTAYBgkqhkiG9w0BCQMxCwYJ
// SIG // KoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xNDA0MjQx
// SIG // ODM5MTRaMCMGCSqGSIb3DQEJBDEWBBRnYRbUA5klDvo8
// SIG // l2tR1uA9xRqQZzANBgkqhkiG9w0BAQUFAASCAQCq74W8
// SIG // j9ClWBxeU+RdpojHCSkw/u0C5+An59bl+4iAljNpSmt8
// SIG // HjLkFgP201HF+snTBNubzH9CoN1oCaKqIMoWwYkM8Sxp
// SIG // 7Uf8HgluvG/a+dp4DsO1sdS0w8WjhjOAEhdAKuAPqYyf
// SIG // TNUAvQHxKJvqhqplKXws9O7g2H1/GJRs/zTAF3hQxDdz
// SIG // m60CSgd4U0MoeYfPu/EocdLAGNXLfIvoKRJx7r0HCKpK
// SIG // 5tCl54cBdv0T/boHophAZBacF21PGDinWMQ0F35DrABX
// SIG // dfmR/EdVGm3+g39R2DHyn29ICTNppqMZJI9ND4+1hD9j
// SIG // DQOgmiRXlzebv7EakCBmsB39DExl
// SIG // End signature block
